import 'angular';
import 'angular-bootstrap';
import 'angular-ui-router';
import 'angular-translate';
import './templates-app'; // autogenerated
import '../services/storage';
import './shell';
import './login';

angular.element(document).ready(() => {

  angular
    .module('NodetomationApp', [
      'ui.bootstrap',
      'templates-app',
      'pascalprecht.translate',
      'NodetoStorageModule',
      'NodetoShellModule',
      'NodetoLoginModule'
    ])
    .config($translateProvider => {
      $translateProvider.useSanitizeValueStrategy(null);
      $translateProvider.translations('en', {
        texts: {
          dashboard: 'Dashboard',
          off: 'OFF',
          on: 'ON',
          schedules: 'Schedules',
          shutdown: 'Shutdown',
          turnOffAll: 'All OFF',
          turnOnAll: 'All ON'
        }
      });
      $translateProvider.translations('es', {
        texts: {
          shutdown: 'Bajar servidor',
          turnOffAll: 'Apagar todo',
          turnOnAll: 'Encender todo'
        }
      });
      $translateProvider.preferredLanguage('en');
    });

  angular.bootstrap(document, ['NodetomationApp']);

});